@DTR.Api_HostAddress = http://localhost:5240

POST {{DTR.Api_HostAddress}}/api/attendance/time-in
Accept: application/json
Content-Type: application/json

{
    "StudentID": 1
}

###
GET {{DTR.Api_HostAddress}}/api/attendance/history/1
Accept: application/json

###
POST {{DTR.Api_HostAddress}}/api/attendance/time-out
Accept: application/json
Content-Type: application/json

{
    "StudentID": 1,
    "Remarks": "Feeling unwell."
}

###
POST {{DTR.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "password123"
}